git:
  submodules: false
language: python
python:
  - "2.7"
# command to install dependencies
install:
#  - pip install progress
  - pip install --upgrade pip
  - python setup.py install
#  - fab doc.html
#  - fab build.install
# command to run tests
script: 
  - nosetests -v --nocapture tests/test_pass.py
